name: CI

on: [push]
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: Installed
    - name: "Configure AWS Credentials" Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1.0.1
      with:
        # AWS Access Key ID
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS Secret Access Key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Session Token
        aws-session-token: # optional
        # AWS Region, e.g. us-east-2
        aws-region: us-west-1
        # Whether to set the AWS account ID for these credentials as a secret value, so that it is masked in logs. Valid values are 'true' and 'false'. Defaults to true
        mask-aws-account-id: # optional
